#!/bin/bash

# Instructions to create and push to GitHub repository
echo "Follow these steps to create and push your repository:"
echo ""
echo "1. First, create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: nba-player-stats-mcp"
echo "   - Description: A Model Context Protocol server for NBA player statistics from basketball-reference.com"
echo "   - Make it Public"
echo "   - DON'T initialize with README, .gitignore, or license (we already have them)"
echo ""
echo "2. After creating the repo, run these commands:"
echo ""
echo "git remote add origin https://github.com/ziyadmir/nba-player-stats-mcp.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "Alternative if you use SSH:"
echo "git remote add origin git@github.com:ziyadmir/nba-player-stats-mcp.git"
echo "git branch -M main"
echo "git push -u origin main"